services:
  api-1:
    build: .
    image: index-tts/api:latest
    container_name: indextts-api-1
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /TTD-Data/index-tts/checkpoints-v2:/app/checkpoints
    ports:
      - "380:8000"
    networks:
      - caddy
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]        # 指定第0块 GPU
              capabilities: ["gpu"]
  api-2:
    extends: api-1
    container_name: indextts-api-2
    ports: !override
      - "381:8000"
    deploy: !override
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]        # 指定第1块 GPU
              capabilities: ["gpu"]

networks:
  caddy:
    external: true
    name: caddy