services:
  indextts:
    build: .
    image: index-tts/api:test
    container_name: indextts-api-test
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /TTD-Data/index-tts/checkpoints-v2:/app/checkpoints
    ports:
      - "7800:8000"
    tty: true
    stdin_open: true
    networks:
      - caddy
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]        # 指定第0块 GPU
              capabilities: ["gpu"]

networks:
  caddy:
    external: true
    name: caddy